import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button, ButtonGroup } from "@chakra-ui/react"
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button variant="primary">Button</Button>
        <Button variant="secondary">Button</Button>
      </main>

    </div>
  )
}

export default Home
